### PR TITLE
1 learning objectives

### PR DESCRIPTION
**Pull request by radumg**
mainly 
- add XML comments
- change order of methods so it aligns with extension lifecycle

- make custom menu in `ViewExtension`

image

and if we click `Say hello` it says hello to current PC user name

image

### CODE REVIEW

**Review by teocomi — APPROVED** [review]
Looks good to me!

**Review by andydandy74 — APPROVED** [review]
LGTM

**Review by mjkkirschner — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@radumg I havn't taken a long enough look - is there a reason there are both a .bat file and post build steps?

**Comment by radumg** [comment]
didn't want to deal with deployment in this PR, so left everything as-is.
see PR #10 which removes `.bat` and makes everything work with build events.

**Pull request merged**
