### PR TITLE
move event handling to static class

### PR DESCRIPTION
**Pull request by radumg**
As discussed on the conference call last week, here's what i would suggest for handling events.
This shouldn't be too complicated for people to understand and would teach them good practice to remember to unregister events, etc.

Please feel free to comment, change code 🤓 , shoot it down with a 🚀 launcher, etc 😎 
As a suggestion, we'll merge in only if everyone is happy with it.

### CODE REVIEW

**Review by mjkkirschner — APPROVED** [review]
LGTM

**Review by andydandy74 — APPROVED** [review]
LGTM

**Review by alfarok — APPROVED** [review]

**Review by wynged — APPROVED** [review]
LGTM as well

**Review by teocomi — APPROVED** [review]
👍

**Review by teocomi — APPROVED** [review]
👍

**Comment by radumg** [comment]
thanks everyone 👍

**Pull request merged**
