### PR TITLE
added build events in csproj, added pkg.json, removed unused stuff

### PR DESCRIPTION
**Pull request by teocomi**

### CODE REVIEW

**Review by radumg — CHANGES_REQUESTED** [review]
why get rid of `Events.cs` ? thought we were all ok with that one as it was merged in #4
otherwise looks good.

**Comment by teocomi** [comment]
Nothing wrong with it, but I will introduce it later when it's actually being used...

**Comment by andydandy74** [comment]
How about using one of them in the example, e.g. ```OnCurrentWorkspaceChanged```?
My project is going to be entirely event-free so it would be nice to have that topic covered at least briefly in the Hello Dynamo intro...

**Comment by radumg** [comment]
@teocomi , could we leave the `events` as they were in and we deal with them in separate PR  or in each of our class folders if we want to change something about them ? just so that small bit doesn't hold this up 👍

**Comment by teocomi** [comment]
ok, readded 🤙

**Comment by radumg** [comment]
👏

**Pull request merged**
